spring:
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: http://localhost:9092
          predicates:
            - Path=/resources/**
          filters:
            - RewritePath=/resources/(?<path>.*), /$\{path}

        - id: upload-service
          uri: http://localhost:7011
          predicates:
            - Path=/services/uploads/**
          filters:
            - RewritePath=/services/uploads/(?<path>.*), /$\{path}
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"